dependencies:
  - "@mafalda-sfu/eslint-config": ^0.3.0
  - cspell: ^6.31.1
  - eslint: ^8.41.0
  - husky: ^8.0.3
  - jsdoc-to-markdown: ^8.0.0
  - madge: ^6.1.0
mergeRules:
  .gitignore:
  .npmignore:
scripts:
  docs: npm-run-all docs:*
  docs:madge: madge . --image madge.svg
  docs:readme: cp README.md madge.svg docs/
  lint: npm-run-all lint:*
  lint:cspell: cspell --dot --gitignore "**"
  lint:eslint: eslint .
  predocs: mkdir -p docs/
  prepare:husky: husky install
  pretest: npm-run-all pretest:*
  pretest:lint: npm run lint
  pretest:madge: madge . --circular
type: module
