dependencies:
  - "@mafalda-sfu/eslint-config": ^0.3.0
  - eslint: ^8.41.0
  - husky: ^8.0.3
  - jsdoc-to-markdown: ^8.0.0
mergeRules:
  .gitignore:
  .npmignore:
scripts:
  docs: npm-run-all docs:*
  docs:readme: cp README.md docs/
  lint: eslint .
  predocs: mkdir -p docs/
  prepare:husky: husky install
  pretest: npm run lint
type: module
