dependencies:
  - "@mafalda-sfu/eslint-config": ^0.3.0
  - eslint: ^8.41.0
  - husky: ^8.0.3
  - jsdoc-to-markdown: ^8.0.0
  - npm-run-all: ^4.1.5
mergeRules:
  .npmignore:
scripts:
  docs: cp README.md docs/ && jsdoc2md *.js > docs/API.md
  lint: eslint .
  predocs: mkdir -p docs/
  prepare: npm-run-all prepare:*
  prepare:husky: husky install
  pretest: npm run lint
type: module
