dependencies:
  - "@mafalda-sfu/eslint-config": ^0.3.0
  - cspell: ^6.31.1
  - eslint: ^8.41.0
  - husky: ^8.0.3
  - jscpd: ^3.5.9
  - jsdoc-to-markdown: ^8.0.0
  - madge: ^6.1.0
  - textlint: ^13.3.3
  - textlint-rule-editorconfig: Mafalda-SFU/textlint-rule-editorconfig
mergeRules:
  .cspell.txt:
  .gitignore:
  .npmignore:

# https://eslint.org/docs/latest/contribute/package-json-conventions
scripts:
  # Project development setup
  prepare: run-s prepare:*
  prepare:build: npm run build
  prepare:install-git-hooks: husky install
  docs:madge: madge . --image madge.svg
  # Linters
  lint: run-s 'lint:!(fix)'
  lint:fix: run-s lint:fix:*

  ## Code linters
  lint:code: run-s lint:code:*
  lint:code:circular-dependencies: madge . --circular
  lint:code:duplicated-code: jscpd .
  lint:code:static-analysis: eslint .

  lint:fix:code: run-s lint:fix:code:*
  lint:fix:code:static-analysis: npm run lint:code:static-analysis -- --fix

  ## Docs linters
  lint:docs: run-s lint:docs:*
  lint:docs:readme: standard-readme
  lint:docs:spell-checker: cspell
  lint:text: textlint .

  lint:fix:text: npm run lint:text -- --fix

  # Build for release
  build: run-s build:*

  # Docs generation
  predocs: mkdir -p docs/
  docs: run-s docs:*
  docs:draw-dependencies-graph: madge . --image docs/madge.svg
  pretest: npm-run-all pretest:*
  pretest:lint: npm run lint

  # Release
  release: run-s release:*
type: module
