name: CI
# test, build documentation and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=20.1.0'

      # Dependencies
      - name: Install dependencies
        run: npm ci --verbose
      - name: Install test reporters
        run: |
          npm install --no-save --verbose \
            @mafalda-sfu/test-reporter-json node-test-github-reporter

      # Tests
      - name: Run tests
        run: |
          npm test -- \
            --test-reporter spec \
            --test-reporter-destination stdout \
            --test-reporter node-test-github-reporter \
            --test-reporter-destination stderr \
            --test-reporter=@mafalda-sfu/test-reporter-json \
            --test-reporter-destination=coverage.json

      # Coverage badge
      - name: Export total coverage
        run: |
          export TOTAL=$( \
            cat coverage.json | \
            jq .summary.totals.coveredLinePercent | \
            jq '.*100|round/100' \
          )
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
      - name: Coverage badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          filename: ${{ github.event.repository.name }}.json
          gistID: 27d772a9a3a8a945b34fd9676de40486
          label: Coverage
          maxColorRange: 90
          message: ${{ env.total }}%
          minColorRange: 50
          namedLogo: Jest
          valColorRange: ${{ env.total }}

  publish-docs:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=20.1.0'

      # Dependencies
      - name: Install dependencies
        run: npm ci --verbose

      # Docs
      - name: Generate docs
        run: npm run docs
      - name: Publish docs
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          destination-github-username: Mafalda-SFU
          destination-repository-name: Mafalda-SFU.github.io
          source-directory: docs
          target-directory: docs/${{ github.event.repository.name }}
          user-email: bot@mafalda.io
          user-name: Mafalda bot

  lint-badge:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=20.1.0'

      # Dependencies
      - name: Install dependencies
        run: npm ci --verbose

      # Lint
      - name: Run linter
        run: npm run lint -- --format json > lint.json

      # Bagde
      - name: Export lint warnings
        run: |
          export TOTAL=$( \
            cat lint.json | \
            jq '[].warningCount | add' \
          )
          echo "color=$(( TOTAL==0 ? 0 : 60 ))" >> $GITHUB_ENV
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total lint warnings: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
      - name: Lint badge
        uses: Schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          color: hsl(${{ env.color }}, 100%, 40%)
          filename: ${{ github.event.repository.name }}.json
          gistID: 377761809285c571637ecd886a5cc492
          label: Lint warnings
          message: ${{ env.total }}
          namedLogo: eslint
